#!/usr/bin/env python3
"""Turn an image into splash.h, the boot screen the firmware paints at startup.

The panel keeps showing whatever was last written to it, so the splash needs no
timer: it stays up until the first USB frame overwrites it.

The source artwork is usually much wider than 128 x 128, so by default the
transparent-or-black margin is trimmed off, the remainder is scaled to fit
inside the panel, and the result is centred on black.  That keeps a wide
wordmark as large as it can be instead of cropping its ends off.  A few pixels
of margin are kept so nothing sits flush against the glass edge; --pad 0 turns
that off.  Pass --mode cover to fill the panel and lose the overhanging edges
instead.

Pixels come out as big-endian RGB565 bytes, the same order the USB frame
protocol uses, so the firmware can hand the array straight to SPI or DMA.

    python3 tools/gen_splash.py usb2tft.png -o splash.h
"""

import argparse
import sys

from PIL import Image

WIDTH = 128
HEIGHT = 128


def rgb565_be(r: int, g: int, b: int) -> tuple:
    word = ((r & 0xF8) << 8) | ((g & 0xFC) << 3) | (b >> 3)
    return (word >> 8) & 0xFF, word & 0xFF


def trim_margin(im: Image.Image, threshold: int) -> Image.Image:
    """Drop rows and columns that are darker than threshold on every channel.

    Image.getbbox() only finds a fully black border, and artwork carries a
    faint vignette, so the bounding box is computed from a thresholded copy.
    """
    mask = im.convert("L").point(lambda v: 255 if v > threshold else 0)
    box = mask.getbbox()
    return im if box is None else im.crop(box)


def build(path: str, mode: str, threshold: int, keep_margin: bool, pad: int) -> Image.Image:
    src = Image.open(path)
    if src.mode in ("RGBA", "LA", "P"):
        # Composite onto black so transparency does not come through as white.
        src = src.convert("RGBA")
        flat = Image.new("RGBA", src.size, (0, 0, 0, 255))
        flat.alpha_composite(src)
        src = flat
    src = src.convert("RGB")

    if not keep_margin:
        src = trim_margin(src, threshold)

    out = Image.new("RGB", (WIDTH, HEIGHT), (0, 0, 0))
    box_w, box_h = WIDTH - 2 * pad, HEIGHT - 2 * pad
    if mode == "cover":
        scale = max(box_w / src.width, box_h / src.height)
    else:
        scale = min(box_w / src.width, box_h / src.height)
    size = (max(1, round(src.width * scale)), max(1, round(src.height * scale)))
    scaled = src.resize(size, Image.LANCZOS)
    out.paste(scaled, ((WIDTH - size[0]) // 2, (HEIGHT - size[1]) // 2))
    return out


def emit(im: Image.Image, source: str) -> str:
    data = bytearray()
    for r, g, b in im.getdata():
        data += bytes(rgb565_be(r, g, b))

    lines = [
        "// Generated by tools/gen_splash.py from %s -- do not edit by hand." % source,
        "//",
        "// %d x %d big-endian RGB565, the same byte order the USB frame protocol" % (WIDTH, HEIGHT),
        "// uses, so this array can go straight to SPI or DMA.",
        "#pragma once",
        "",
        "#include <stdint.h>",
        "",
        "#define SPLASH_WIDTH  %d" % WIDTH,
        "#define SPLASH_HEIGHT %d" % HEIGHT,
        "#define SPLASH_BYTES  (SPLASH_WIDTH * SPLASH_HEIGHT * 2)",
        "",
        "static const uint8_t splash_rgb565[SPLASH_BYTES] = {",
    ]
    for i in range(0, len(data), 16):
        chunk = data[i:i + 16]
        lines.append("    " + " ".join("0x%02X," % b for b in chunk))
    lines += ["};", ""]
    return "\n".join(lines)


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__,
                                 formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("image")
    ap.add_argument("-o", "--output", default="splash.h")
    ap.add_argument("--mode", choices=("contain", "cover"), default="contain",
                    help="contain letterboxes the whole image, cover fills and crops")
    ap.add_argument("--keep-margin", action="store_true",
                    help="skip the dark-margin trim and use the image as given")
    ap.add_argument("--threshold", type=int, default=12,
                    help="luma above which a pixel counts as content (default 12)")
    ap.add_argument("--pad", type=int, default=3,
                    help="blank border in pixels kept around the artwork (default 3)")
    ap.add_argument("--preview", metavar="PNG",
                    help="also write the 128x128 result as a PNG to eyeball")
    args = ap.parse_args()

    im = build(args.image, args.mode, args.threshold, args.keep_margin, args.pad)
    with open(args.output, "w") as fh:
        fh.write(emit(im, args.image))
    if args.preview:
        im.save(args.preview)

    print("wrote %s (%d bytes of pixel data) from %s" %
          (args.output, WIDTH * HEIGHT * 2, args.image))
    return 0


if __name__ == "__main__":
    sys.exit(main())
